### ISSUE TITLE
model labeling approach

### ISSUE THREAD

**Issue by idavydov** [sjspielman/pyvolve#1]
Dear Stephanie,
I have been playing with your software and it looks extremely nice and useful.
At the same I think model labeling scheme has a room for improvements.
First of all, putting the model-label after a branch length is usually impossible using most of the tree manipulation software/libraries (e.g. dendropy).
Second, "sticky" (propagating to children) model labeling makes it difficult use pyvolve in a very common case, when you want to label a single branch. Also the behavior differs depending on the tree rooting. And last but not least, this implicit propagation is kinda against python zen ("Explicit is better than implicit") :)
What do you think about using codeml-like model-labeling?
It could look like this:
```
(t4:0.785,(t3:0.380,(t2:0.806,(t5:0.612,t1:0.660)#m1:0.762)#m2:0.921):0.207);
```
There are plenty of variations depending on your taste.  `#m1#` should also work.
Optionally you could have the flag to propagate the model label, e.g. `#m1!` or `#m1!#`.

This way you can easily read & write model labels as a node label suffix in any standard software.

I probably will try to implement this in pyvolve, the code looks good and easy to read and write. 

If you also think this could be useful for others, we can agree on the modifications and I can send you a pull-request on github.

Cheers,
Iakov

**Comment by sjspielman** [comment]
Hi Iakov,

You are more than welcome to implement any of the changes you wish to see
and submit a pull request on github. However, I am very wary about changing
the specific syntax for node labeling, given that several labs are using
the library and I don't want to introduce backwards compatibility issues.

With that said, you are welcome to work with the code and I'll look for a
pull request if you decide to go ahead with any re-implementations.

Best,
Stephanie

On Tue, Jan 12, 2016 at 12:02 PM, idavydov <notifications@github.com> wrote:

> Dear Stephanie,
> I have been playing with your software and it looks extremely nice and
> useful
> At the same I think model labeling scheme has a room for improvements
> First of all, putting the model-label after a branch length is usually
> impossible using most of the tree manipulation software/libraries (eg
> dendropy)
> Second, "sticky" (propagating to children) model labeling makes it
> difficult use pyvolve in a very common case, when you want to label a
> single branch Also the behavior differs depending on the tree rooting And
> last but not least, this implicit propagation is kinda against python zen
> ("Explicit is better than implicit") :)
> What do you think about using codeml-like model-labeling?
> It could look like this:
>
> (t4:0785,(t3:0380,(t2:0806,(t5:0612,t1:0660)#m1:0762)#m2:0921):0207);
>
> There are plenty of variations depending on your taste #m1# should also
> work
> Optionally you could have the flag to propagate the model label, eg #m1!
> or #m1!#
>
> This way you can easily read & write model labels as a node label suffix
> in any standard software
>
> I probably will try to implement this in pyvolve, the code looks good and
> easy to read and write
>
> If you also think this could be useful for others, we can agree on the
> modifications and I can send you a pull-request on github
>
> Cheers,
> Iakov
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sjspielman/pyvolve/issues/1>.
>



-- 
Stephanie J. Spielman
Ph.D. Candidate, Wilke Lab
Department of Integrative Biology
Center for Computational Biology and Bioinformatics
University of Texas at Austin
