### ISSUE TITLE
Unable to Load Single-Node Trees

### ISSUE THREAD

**Issue by niemasd** [sjspielman/pyvolve#11]
Currently, it seems as though the Newick parser in Pyvolve does not allow single-node trees, e.g. `N13|4|3.0:3;`. For example, the following chunk of code:

```python
treestr = "N13|4|3.0:3;"
import pyvolve
tree = pyvolve.read_tree(tree=treestr)
```

results in the following error:

```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/pyvolve/newick.py", line 119, in read_tree
    (tree, flags, internalNode_count, index) = _parse_tree(tstring, flags, internalNode_count, scale_tree, 0) 
  File "/usr/local/lib/python3.6/site-packages/pyvolve/newick.py", line 316, in _parse_tree
    assert(tstring[index]=='(')
AssertionError
```

**Comment by niemasd** [comment]
I wrote a [fairly simple Newick parser](https://niemasd.github.io/TreeSwift/_modules/treeswift/Tree.html#read_tree_newick) in my own package, [TreeSwift](https://github.com/niemasd/TreeSwift/wiki), that handles trees like this. Feel free to reuse the logic if you wish to implement this ability:

**Comment by sjspielman** [comment]
Hi @niemasd, 

pyvolve will read in this tree fine if it has parentheses, which is a required component of newick format:

```
>>> from pyvolve import *
>>> t = "(N13|4|3.0:3);"
>>> tree = read_tree(tree = t)
>>> tree
<pyvolve.newick.Node instance at 0x10e250368>
>>> print_tree(tree)
root None None
	N13|4|3.0 3.0 None
```

This will set up a simulation for a single root sequence along a branch with length of 3.0

Best, 
Stephanie

**Comment by niemasd** [comment]
Ah, excellent, thank you for the help!
