### ISSUE TITLE
Feature request, set seed

### ISSUE THREAD

**Issue by dschrempf** [sjspielman/pyvolve#14]
Hello,

as far as I can see, it is not possible to set the seed when evolving a sequence.

Thank you!

**Comment by sjspielman** [comment]
By default, pyvolve will set the random seed to a new random number for every simulation. I can add an option for this, but it won't be in the LG fix release I just made. I'll add this feature in to the master branch, so you can download from source to use this feature.

**Comment by dschrempf** [comment]
Thank you very much and glad that I could help!
