### ISSUE TITLE
random seed cannot be set as float, should be int? (using numpy 1.21.2)

### ISSUE THREAD

**Issue by rhr** [sjspielman/pyvolve#22]
https://github.com/sjspielman/pyvolve/blob/a6e7dc128b7d834117330d062bc66f56b4c71804/src/evolver.py#L167

Also, numpy seems to have a new API for random numbers
https://numpy.org/doc/stable/reference/random/generator.html#numpy.random.default_rng

**Comment by sjspielman** [comment]
This has been fixed (both the float bug and updating to current numpy version of random code) and merged into master. It will be included in a new minor release in the next week.
