### ISSUE TITLE
pyvolve in Python3?

### ISSUE THREAD

**Issue by jbloom** [sjspielman/pyvolve#5]
Hi @sjspielman,

I'm using `pyvolve` for a class I'm teaching. Some of the students tried to use it with `python3`. Although it installs just fine using `pip` for `python3`, it doesn't seem to work. In `python3`, `import pyvolve` gives the following:

    >>> import pyvolve
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/home/jbloom/.local/lib/python3.4/site-packages/pyvolve/__init__.py", line 29, in <module>
        from .model import *
      File "/home/jbloom/.local/lib/python3.4/site-packages/pyvolve/model.py", line 16, in <module>
        from matrix_builder import *
    ImportError: No module named 'matrix_builder'

So it appears to me that `pyvolve` currently doesn't work with `python3`, is that correct?

If so, perhaps you could make the `setup.py` file throw an error if someone tries to `pyvolve` it with `python3`? That way people would know it is incompatible with their Python version. You could add something like: https://github.com/jbloomlab/phydms/blob/master/setup.py#L17-L18

**Comment by sjspielman** [comment]
Good find - the relative module imports need to be updated for Python3. I have just made a new release (v0.8) which is fully compatible w/ Python 3.5 (works on my computer with pip3 install, and python3 interpreter). Should be good to go for either Python version now.

**Comment by jbloom** [comment]
Thanks @sjspielman. But during change, small bug introduced due to no end-of-string character in version specification. This now causes import problems for me.
https://github.com/sjspielman/pyvolve/blob/master/src/__init__.py#L28

**Comment by sjspielman** [comment]
Argh, sorry! Give me 2 minutes and wait for 0.8.1..

On Sunday, May 15, 2016, Jesse Bloom <notifications@github.com> wrote:

> Thanks @sjspielman <https://github.com/sjspielman>. But during change,
> small bug introduced due to no end-of-string character in version
> specification. This now causes import problems for me.
> https://github.com/sjspielman/pyvolve/blob/master/src/__init__.py#L28
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/sjspielman/pyvolve/issues/5#issuecomment-219305571>
>


-- 
Stephanie J. Spielman
Ph.D. Candidate, Wilke Lab
Department of Integrative Biology
Center for Computational Biology and Bioinformatics
University of Texas at Austin

**Comment by jbloom** [comment]
Great, thanks. Now works for me on Python 3.4.3 and 2.7.10

**Comment by sjspielman** [comment]
Real quick, update one more time (still v0.8.1, the pip version has been replaced). There was a small issue w/ a print statement in the test suite that's now been fixed (although if you never run tests then don't bother).
