### ISSUE TITLE
pyvolve packaged for bioconda: new easy and reproducible installation option

### ISSUE THREAD

**Issue by dlaehnemann** [sjspielman/pyvolve#9]
Dear @sjspielman ,

thank you for providing this nicely implemented python module!

I just wanted to let you know that I have packaged the most recent version of `pyvolve` (`0.8.7`) for [bioconda](https://bioconda.github.io/), a channel for the platform-independent package management tool [conda](https://conda.io/docs/). I use this tool to make installation in analysis pipelines reproducible for other users.

I hope that I have included all the correct licensing and attribution infos in the recipe, but please let me know in case you would like anything added -- this is easily updated. Currently, this info is visible on the anaconda website and in the GitHub repository for the recipe:

* <https://anaconda.org/bioconda/pyvolve>
* <https://github.com/bioconda/bioconda-recipes/blob/master/recipes/pyvolve/meta.yaml>

`pyvolve` will also become searchable through the bioconda `Available packages` search, probably overnight: <https://bioconda.github.io/recipes.html>

In case you wish to offer this mode of installation to your users, you might add the following to your README.md:

    Another way to install pyvolve is via [bioconda](https://bioconda.github.io/). For the required one time setup of conda and bioconda, please refer to [bioconda's installation instructions](https://bioconda.github.io/#using-bioconda). Once this is done, all you need to do is issue the following command:
    
    ```
    conda install pyvolve
    ```

Should you want to update the bioconda recipe at any point, I would be glad to help, even though the [contribution instructions for bioconda](https://bioconda.github.io/contributing.html) are a pretty much self-explanatory walk-through. Otherwise, I will also update that recipe whenever I need a newer version of pyvolve for the respective pipeline.

Best regards,
David

**Comment by sjspielman** [comment]
Hi @dlaehnemann , 

This is really useful, thanks for your efforts!

Best,
Stephanie
